version: '3.8'

services:
  postgres:
    image: postgres
    container_name: mnist_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: helterskelt34
      POSTGRES_DB: mnist_logs
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # Auto-runs init script to create table if not exists

  streamlit_app:
    build: .
    container_name: mnist_streamlit
    restart: always
    ports:
      - "8501:8501"
    depends_on:
      - postgres
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=helterskelt34
      - DATABASE_NAME=mnist_logs

volumes:
  postgres_data:
